apiVersion: v1
kind: Service
metadata:
  name: retail-app-service
spec:
  selector:
    app: retail-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80               # Internal Kubernetes service port
      targetPort: 32768      # Your container's port
      nodePort: 32000        # Exposed on the host (use this in browser)